var no = 3.4;
var str = "Hrishi";
var bool = true;
var abc;
var xyz = null;
console.log(typeof (no));
console.log(typeof (str));
console.log(typeof (bool));
console.log(typeof (abc));
console.log(typeof (xyz));
